apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "new-gateway.fullname" . }}
  labels:
    app: {{ template "new-gateway.name" . }}
    chart: {{ template "new-gateway.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: {{ template "new-gateway.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "new-gateway.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.containerPort }}
              protocol: TCP
          readinessProbe:
            httpGet:
              path: {{ .Values.health.readinessProbe.path }}
              port: http
              #port: { { .Values.service.internalPort } }
            initialDelaySeconds: {{ .Values.health.readinessProbe.initialDelaySeconds }}
            timeoutSeconds: {{ .Values.health.readinessProbe.timeoutSeconds }}
            periodSeconds: {{ .Values.health.readinessProbe.periodSeconds }}
            failureThreshold: {{ .Values.health.readinessProbe.failureThreshold }}
          livenessProbe:
            httpGet:
              path: {{ .Values.health.livenessProbe.path }}
              #port: { { .Values.service.internalPort } }
              port: http
            initialDelaySeconds: {{ .Values.health.livenessProbe.initialDelaySeconds }}
            timeoutSeconds: {{ .Values.health.livenessProbe.timeoutSeconds }}
            periodSeconds: {{ .Values.health.livenessProbe.periodSeconds }}
            failureThreshold: {{ .Values.health.livenessProbe.failureThreshold }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
